# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod "maestrodev/wget"
mod "portertech/mongodb"
mod "puppetlabs/stdlib"
mod "puppetlabs/apt"
mod "cirrax/puppetlabs-rabbitmq",
    :git => "https://github.com/cirrax/puppetlabs-rabbitmq.git"
mod "puppetlabs/apache"
mod "garethr/erlang"
mod "saz/timezone"
